servicio:
    pattern:  /
    defaults: { _controller: "ProductoBundle:Servicio:index" }

servicio_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProductoBundle:Servicio:show" }

servicio_new:
    pattern:  /new
    defaults: { _controller: "ProductoBundle:Servicio:new" }

servicio_create:
    pattern:  /create
    defaults: { _controller: "ProductoBundle:Servicio:create" }
    requirements: { _method: post }

servicio_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProductoBundle:Servicio:edit" }

servicio_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProductoBundle:Servicio:update" }
    requirements: { _method: post }

servicio_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProductoBundle:Servicio:delete" }
    requirements: { _method: post }
